import 'package:supabase_flutter/supabase_flutter.dart';

class RegistrationService {
  // Access the central Supabase database client instance
  static final _supabase = Supabase.instance.client;

  static Future<void> saveApplicant({
    required String firstName,
    required String lastName,
    required String idNumber,
    required String dateOfBirth,
    required String gender,
    required String contactNumber,
    required String email,
    required String residentialArea,
    required String highestQualification,
    required String employmentStatus,
    required List<String> skills,
    String programmeHistory = '',
    String applicationStatus = 'Pending',
  }) async {
    // 1. Fetch the unique system ID generated by Supabase Auth for this specific session
    final user = _supabase.auth.currentUser;
    if (user == null) {
      throw Exception('Cannot save profile data: No authenticated user session found.');
    }

    // 2. Build the matching data row payload map structured precisely to the SQL schema definition names
    final applicantData = {
      'id': user.id, // Links the profile to the auth account record row
      'first_name': firstName,
      'last_name': lastName,
      'id_number': idNumber,
      'date_of_birth': dateOfBirth,
      'gender': gender,
      'contact_number': contactNumber,
      'email': email,
      'residential_area': residentialArea,
      'highest_qualification': highestQualification,
      'current_employment_status': employmentStatus,
      'skills': skills, // Supabase natively parses list arrays
      'programme_history': programmeHistory,
      'application_status': applicationStatus,
    };

    // 3. Perform a real-time network insert directly to your public cloud table
    await _supabase
        .from('applicants')
        .insert(applicantData);
  }

  /// Helper fetch method to read applicant profiles out of your database instance table
  static Future<List<Map<String, dynamic>>> getApplicants() async {
    final response = await _supabase
        .from('applicants')
        .select();
    return List<Map<String, dynamic>>.from(response);
  }
}
