import 'package:supabase_flutter/supabase_flutter.dart';

class RegistrationService {
  // Access the central Supabase database client instance
  static final _supabase = Supabase.instance.client;

  /// Saves the extended applicant profile to the 'applicants' table.
  /// Matches the schema provided in the database diagram.
  static Future<void> saveApplicant({
    required String firstName,
    required String lastName,
    required String idNumber,
    required String dateOfBirth, // Expected format: DD/MM/YYYY from UI
    required String gender,
    required String email,
    required String residentialArea,
    required String highestQualification,
    required String employmentStatus,
    required List<String> skills,
  }) async {
    // 1. Fetch the unique system ID generated by Supabase Auth for this specific session
    final user = _supabase.auth.currentUser;
    if (user == null) {
      throw Exception('Cannot save profile data: No authenticated user session found.');
    }

    // 2. Format Date: Convert DD/MM/YYYY (UI) to YYYY-MM-DD (Postgres)
    String formattedDate = dateOfBirth;
    try {
      final parts = dateOfBirth.split('/');
      if (parts.length == 3) {
        formattedDate = '${parts[2]}-${parts[1].padLeft(2, '0')}-${parts[0].padLeft(2, '0')}';
      }
    } catch (e) {
      // Fallback to original if parsing fails, Supabase might still reject it if invalid
    }

    // 3. Build the payload matching the schema image columns exactly
    final applicantData = {
      'user_id': user.id,
      'first_name': firstName,
      'last_name': lastName,
      'id_number': idNumber,
      'date_of_birth': formattedDate,
      'gender': gender,
      'email_address': email,
      'residential_area': residentialArea,
      'highest_qualification': highestQualification,
      'current_employment_status': employmentStatus,
      'skills': skills, // ✅ FIXED: Pass List<String> directly — Supabase converts to array
      'role': 'applicant',
      'updated_at': DateTime.now().toIso8601String(),
    };

    // 4. Use upsert to prevent duplicate errors if registration is retried
    await _supabase
        .from('applicants')
        .upsert(applicantData, onConflict: 'user_id');
  }

  /// Helper fetch method to read applicant profiles out of your database instance table
  static Future<List<Map<String, dynamic>>> getApplicants() async {
    final response = await _supabase
        .from('applicants')
        .select();
    return List<Map<String, dynamic>>.from(response);
  }
}